image: node:16.19.0-bullseye

stages:
  - lint-check
  - audit

lint-check:
  stage: lint-check
  before_script:
    - npm i --silent
  script:
    - npm run lint:check
  only:
    - development
    - master
    - merge_requests

audit:
  stage: audit
  before_script:
    - npm i --package-lock-only --silent
  script:
    - npm audit --audit-level=critical
  only:
    - development
    - master
    - merge_requests
