stages:
  - format-check
  - test

format-check:
  image: node:16.19.0-bullseye
  stage: format-check
  before_script:
    - npm install --silent
  script:
    - npm run format-check
  only:
    - development
    - master
    - merge_requests

sast:
  stage: test
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "development"'
include:
- template: Security/SAST.gitlab-ci.yml
