include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - format-check
  - audit
  - test

format-check:
  image: node:16.19.0-bullseye
  stage: format-check
  before_script:
    - npm install --silent
  script:
    - npm run format-check
  only:
    - development
    - master
    - merge_requests

audit:
  image: node:16.19.0-bullseye
  stage: audit
  script:
    - npm audit --audit-level=critical
  only:
    - development
    - master
    - merge_requests

sast:
  stage: test
  allow_failure: true
