image: node:16.19-bullseye

stages:
  - lint-check
  - audit
  - build

lint-check:
  stage: lint-check
  before_script:
    - npm i --silent
  script:
    - npm run lint:check
  only:
    - development
    - master
    - merge_requests

audit:
  stage: audit
  allow_failure: true
  script:
    - npm audit --audit-level=critical
  only:
    - development
    - master
    - merge_requests

build:
  stage: build
  before_script:
    - npm i --silent
  script:
    - npm run build
  only:
    - development
    - merge_requests

build-deploy:
  stage: build
  before_script:
    - npm i --silent
  after_script:
    - curl -X POST "https://jenkins.gtomy.net/generic-webhook-trigger/invoke?token=$JENKINS_DEPLOY_HOOK_TOKEN"
  script:
    - npm run build
  only:
    - master
