include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - format-check
  - audit
  - test

format-check:
  image: node:16.19.0-bullseye
  stage: format-check
  before_script:
    - npm i --silent
  script:
    - npm run format-check
  only:
    - development
    - master
    - merge_requests

audit:
  image: node:16.19.0-bullseye
  stage: audit
  before_script:
    - npm i --package-lock-only --silent
  script:
    - npm audit --audit-level=critical
  only:
    - development
    - master
    - merge_requests

sast:
  stage: test
  allow_failure: true
