image: node:18.17-bullseye

stages:
  - lint-check
  - audit
  - build
  - deploy
  - storybook

lint-check:
  stage: lint-check
  before_script:
    - npm i --silent
  script:
    - npm run lint:check
  only:
    - development
    - master
    - merge_requests

audit:
  stage: audit
  allow_failure: true
  script:
    - npm audit --audit-level=critical
  only:
    - development
    - master
    - merge_requests

build:
  stage: build
  before_script:
    - npm i --silent
  script:
    - npm run build
  only:
    - development
    - master
    - merge_requests

deploy:
  stage: deploy
  script:
    - curl -X POST "https://jenkins.gtomy.net/generic-webhook-trigger/invoke?token=$JENKINS_DEPLOY_HOOK_TOKEN"
  only:
    - master

pages:
  stage: storybook
  allow_failure: true
  before_script:
    - npm i --silent
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - public
  only:
    - master
