image: node:18.17-bullseye

stages:
  - lint-check
  - audit
  - build
  - deploy
  - storybook

lint-check:
  stage: lint-check
  before_script:
    - npm i --silent
  script:
    - npm run lint:check
  only:
    - main
    - merge_requests

audit:
  stage: audit
  allow_failure: true
  script:
    - npm audit --audit-level=critical
  only:
    - main
    - merge_requests

build:
  stage: build
  artifacts:
    untracked: true
  before_script:
    - npm i --silent
  script:
    - npm run build
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "//registry.npmjs.org/:_authToken=${CI_NPM_TOKEN}" > .npmrc
    - npm publish
  only:
    - web

pages:
  stage: storybook
  allow_failure: true
  before_script:
    - npm i --silent
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - public
  only:
    - web
